### ISSUE TITLE
How can I use this to backup my terms sets?

### ISSUE THREAD

**Issue by talismax** [bandrben/SPTaxonomyToolsOnline#1]
In testing I've done an advanced export to a text file, deleted the term set and then tried to restore it with an advanced import from the text file. This results in an error:

10:56:11 AM: ERROR: Microsoft.SharePoint.Client.ServerException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at SPTaxonomyToolsOnline.Form1.LoadTStoreTGroupTSet(ClientContext ctx, TaxonomySession session, TermStore& store, TermGroup& group, TermSet& set) in C:\Users\KyleReed\Downloads\SPTaxonomyToolsOnline-master\SPTaxonomyToolsOnline-master\SPTaxonomyToolsOnline\Form1.cs:line 385
   at SPTaxonomyToolsOnline.Form1.ImportTermsAdv() in C:\Users\KyleReed\Downloads\SPTaxonomyToolsOnline-master\SPTaxonomyToolsOnline-master\SPTaxonomyToolsOnline\Form1.cs:line 921
   at SPTaxonomyToolsOnline.Form1.bgw_btnStartImport(Object sender, DoWorkEventArgs e) in C:\Users\KyleReed\Downloads\SPTaxonomyToolsOnline-master\SPTaxonomyToolsOnline-master\SPTaxonomyToolsOnline\Form1.cs:line 841
10:56:11 AM: Log saved to EXE folder.

I'm looking for a backup and restore tool because a few hundred terms went missing in O365 yesterday and MS says they don't know what happened and they aren't interested in finding out. My backup provider doesn't backup the managed metadata service.

**Comment by bandrben** [comment]
If you are still having this problem hit me up at bsteinhauser [ at ] bandrsolutions [ dot  ] com.
